## TALLER APIs

In [3]:
import pandas as pd
import requests

# 1. Consulta de la API

url = "https://www.datos.gov.co/api/v3/views/cuit-be64/query.json"
respuesta = requests.get(url)

if respuesta.status_code == 200:
    print("Código de estado:", respuesta.status_code)

    datos_json = respuesta.json()

    df_datos = pd.DataFrame(datos_json)

    display(df_datos.head())
else:
    print(
        f"Error al conectar con Datos Abiertos. Código de estado: {respuesta.status_code}"
    )

Código de estado: 200

,:id,:version,:created_at,:updated_at,nit,razon_social,a_o,mes,municipio,estrato,no_suscriptores_acueducto,consumo_m3_acueducto,promedio_consumo_acueducto,no_suscriptores_alcantarillado,consumo_m3_alcantarillado,promedio_consumo_alcantarillado
0,row-fsy9.upn9-iucj,rv-v9zq-6v6w~i27s,2025-10-16T13:43:37.713Z,2025-10-16T13:43:37.713Z,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,Estrato1,1295,10762,8.31,1182,9829,8.32
1,row-rtn2-57tk~euwv,rv-gmp3~68aw~pwb9,2025-10-16T13:43:37.713Z,2025-10-16T13:43:37.713Z,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,Estrato2,2670,22558,8.45,2493,21300,8.54
2,row-u3ce-yhhp~jset,rv-uevt-f9fz_6n62,2025-10-16T13:43:37.713Z,2025-10-16T13:43:37.713Z,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,Estrato3,468,4496,9.61,462,4312,9.33
3,row-wiqw-nnvd-zvjm,rv-jzcj.9fw9~325v,2025-10-16T13:43:37.713Z,2025-10-16T13:43:37.713Z,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,Estrato4,11,93,8.45,10,73,7.3
4,row-kpk2_bibv~rbzw,rv-zv8p~wk5y-vbxx,2025-10-16T13:43:37.713Z,2025-10-16T13:43:37.713Z,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,Estrato5,1,19,19.00,0,0,0

In [4]:
## Limpieza de datos
  ## Eliminar columnas

columnas_a_eliminar = [':id', ':version', ':created_at', ':updated_at']
df_limpio = df_datos.drop(columns=columnas_a_eliminar, errors='ignore')

# Renombrar columnas 
df_limpio = df_limpio.rename(columns={
    'a_o': 'Año',
    'razon_social': 'Empresa',
    'no_suscriptores_acueducto': 'Suscriptores Acueducto',
    'consumo_m3_acueducto':'Consumo M3 Agua',
    'promedio_consumo_acueducto': 'Promedio Consumo Agua',
    'no_suscriptores_alcantarillado':'Suscriptores Alcantarillado',
    'consumo_m3_alcantarillado':'Consumo M3 Alcantarillado',
    'promedio_consumo_alcantarillado':'Promedio Consumo Alcantarillado'
})

## Eliminar la palabra estrato en los datos
if 'estrato' in df_limpio.columns:
    df_limpio['estrato'] = df_limpio['estrato'].str.replace('Estrato', '', case=False).str.strip()

In [5]:
display(df_limpio.head())

,nit,Empresa,Año,mes,municipio,estrato,Suscriptores Acueducto,Consumo M3 Agua,Promedio Consumo Agua,Suscriptores Alcantarillado,Consumo M3 Alcantarillado,Promedio Consumo Alcantarillado
0,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,1,1295,10762,8.31,1182,9829,8.32
1,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,2,2670,22558,8.45,2493,21300,8.54
2,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,3,468,4496,9.61,462,4312,9.33
3,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,4,11,93,8.45,10,73,7.3
4,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,5,1,19,19.00,0,0,0

In [ ]:
## Exportar database en un archivo .CSV

nombre_archivo = "dataset_acueducto_alcantarillado.csv"

df_limpio.to_csv(nombre_archivo, index=False, encoding="utf-8-sig")

print(f"\n¡Dataset procesado con éxito!")
print(f"Archivo guardado en tu directorio local como: '{nombre_archivo}'")


display(df_limpio.head())

¡Dataset procesado con éxito!
Archivo guardado en tu directorio local como: 'dataset_acueducto_alcantarillado.csv'

,nit,Empresa,Año,mes,municipio,estrato,Suscriptores Acueducto,Consumo M3 Agua,Promedio Consumo Agua,Suscriptores Alcantarillado,Consumo M3 Alcantarillado,Promedio Consumo Alcantarillado
0,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,1,1295,10762,8.31,1182,9829,8.32
1,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,2,2670,22558,8.45,2493,21300,8.54
2,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,3,468,4496,9.61,462,4312,9.33
3,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,4,11,93,8.45,10,73,7.3
4,890.803.239-9,Empresa de Obras Sanitarias de Caldas - Empoca...,2025,ENERO,AGUADAS,5,1,19,19.00,0,0,0